-- 创建邮件表
CREATE TABLE IF NOT EXISTS `im_email` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `sender_id` bigint(20) DEFAULT NULL COMMENT '发送者ID',
  `sender_name` varchar(100) DEFAULT NULL COMMENT '发送者名称',
  `sender_email` varchar(100) DEFAULT NULL COMMENT '发送者邮箱',
  `receiver_id` bigint(20) DEFAULT NULL COMMENT '接收者ID',
  `subject` varchar(255) DEFAULT NULL COMMENT '邮件主题',
  `html_content` longtext COMMENT '邮件内容（HTML格式）',
  `text_content` longtext COMMENT '纯文本内容',
  `is_read` tinyint(1) DEFAULT '0' COMMENT '是否已读',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否已删除（软删除）',
  `is_starred` tinyint(1) DEFAULT '0' COMMENT '是否星标',
  `folder` varchar(20) DEFAULT 'INBOX' COMMENT '邮件文件夹：INBOX/SENT/DRAFTS/SPAM/TRASH',
  `attachment_count` int(11) DEFAULT '0' COMMENT '附件数量',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `receive_time` datetime DEFAULT NULL COMMENT '接收时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_receiver_id` (`receiver_id`),
  KEY `idx_sender_id` (`sender_id`),
  KEY `idx_folder` (`folder`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_receiver_folder` (`receiver_id`, `folder`),
  KEY `idx_receiver_read_deleted` (`receiver_id`, `is_read`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='邮件表';