package com.ruoyi.im.util;

import java.util.HashMap;
import java.util.Map;

/**
 * 拼音工具类
 * 用于将中文转换为拼音首字母，支持搜索功能
 *
 * @author ruoyi
 */
public class PinyinUtil {

    /**
     * 拼音首字母映射表
     * 包含常用汉字的首字母映射
     */
    private static final Map<Character, String> PINYIN_MAP = new HashMap<>();

    static {
        // A
        PINYIN_MAP.put('阿', "A");
        PINYIN_MAP.put('啊', "A");
        // B
        PINYIN_MAP.put('八', "B");
        PINYIN_MAP.put('巴', "B");
        PINYIN_MAP.put('拔', "B");
        PINYIN_MAP.put('吧', "B");
        PINYIN_MAP.put('白', "B");
        PINYIN_MAP.put('百', "B");
        PINYIN_MAP.put('班', "B");
        PINYIN_MAP.put('般', "B");
        PINYIN_MAP.put('半', "B");
        PINYIN_MAP.put('包', "B");
        PINYIN_MAP.put('宝', "B");
        PINYIN_MAP.put('保', "B");
        PINYIN_MAP.put('报', "B");
        PINYIN_MAP.put('贝', "B");
        PINYIN_MAP.put('本', "B");
        PINYIN_MAP.put('比', "B");
        PINYIN_MAP.put('必', "B");
        PINYIN_MAP.put('边', "B");
        PINYIN_MAP.put('便', "B");
        PINYIN_MAP.put('别', "B");
        PINYIN_MAP.put('变', "B");
        PINYIN_MAP.put('宾', "B");
        PINYIN_MAP.put('冰', "B");
        PINYIN_MAP.put('波', "B");
        PINYIN_MAP.put('伯', "B");
        PINYIN_MAP.put('博', "B");
        PINYIN_MAP.put('不', "B");
        PINYIN_MAP.put('步', "B");
        PINYIN_MAP.put('布', "B");
        PINYIN_MAP.put('部', "B");
        // C
        PINYIN_MAP.put('才', "C");
        PINYIN_MAP.put('材', "C");
        PINYIN_MAP.put('采', "C");
        PINYIN_MAP.put('彩', "C");
        PINYIN_MAP.put('参', "C");
        PINYIN_MAP.put('餐', "C");
        PINYIN_MAP.put('残', "C");
        PINYIN_MAP.put('仓', "C");
        PINYIN_MAP.put('草', "C");
        PINYIN_MAP.put('策', "C");
        PINYIN_MAP.put('层', "C");
        PINYIN_MAP.put('曾', "C");
        PINYIN_MAP.put('叉', "C");
        PINYIN_MAP.put('查', "C");
        PINYIN_MAP.put('差', "C");
        PINYIN_MAP.put('产', "C");
        PINYIN_MAP.put('长', "C");
        PINYIN_MAP.put('常', "C");
        PINYIN_MAP.put('场', "C");
        PINYIN_MAP.put('唱', "C");
        PINYIN_MAP.put('车', "C");
        PINYIN_MAP.put('彻', "C");
        PINYIN_MAP.put('陈', "C");
        PINYIN_MAP.put('诚', "C");
        PINYIN_MAP.put('成', "C");
        PINYIN_MAP.put('承', "C");
        PINYIN_MAP.put('城', "C");
        PINYIN_MAP.put('吃', "C");
        PINYIN_MAP.put('充', "C");
        PINYIN_MAP.put('出', "C");
        PINYIN_MAP.put('除', "C");
        PINYIN_MAP.put('楚', "C");
        PINYIN_MAP.put('川', "C");
        PINYIN_MAP.put('传', "C");
        PINYIN_MAP.put('船', "C");
        PINYIN_MAP.put('窗', "C");
        PINYIN_MAP.put('床', "C");
        PINYIN_MAP.put('春', "C");
        PINYIN_MAP.put('次', "C");
        PINYIN_MAP.put('从', "C");
        PINYIN_MAP.put('粗', "C");
        PINYIN_MAP.put('促', "C");
        PINYIN_MAP.put('催', "C");
        PINYIN_MAP.put('村', "C");
        PINYIN_MAP.put('存', "C");
        PINYIN_MAP.put('错', "C");
        // D
        PINYIN_MAP.put('达', "D");
        PINYIN_MAP.put('大', "D");
        PINYIN_MAP.put('代', "D");
        PINYIN_MAP.put('带', "D");
        PINYIN_MAP.put('待', "D");
        PINYIN_MAP.put('单', "D");
        PINYIN_MAP.put('但', "D");
        PINYIN_MAP.put('淡', "D");
        PINYIN_MAP.put('当', "D");
        PINYIN_MAP.put('党', "D");
        PINYIN_MAP.put('导', "D");
        PINYIN_MAP.put('到', "D");
        PINYIN_MAP.put('的', "D");
        PINYIN_MAP.put('得', "D");
        PINYIN_MAP.put('德', "D");
        PINYIN_MAP.put('登', "D");
        PINYIN_MAP.put('等', "D");
        PINYIN_MAP.put('低', "D");
        PINYIN_MAP.put('底', "D");
        PINYIN_MAP.put('地', "D");
        PINYIN_MAP.put('点', "D");
        PINYIN_MAP.put('电', "D");
        PINYIN_MAP.put('店', "D");
        PINYIN_MAP.put('调', "D");
        PINYIN_MAP.put('定', "D");
        PINYIN_MAP.put('东', "D");
        PINYIN_MAP.put('冬', "D");
        PINYIN_MAP.put('动', "D");
        PINYIN_MAP.put('都', "D");
        PINYIN_MAP.put('读', "D");
        PINYIN_MAP.put('度', "D");
        PINYIN_MAP.put('短', "D");
        PINYIN_MAP.put('对', "D");
        PINYIN_MAP.put('多', "D");
        PINYIN_MAP.put('朵', "D");
        // E
        PINYIN_MAP.put('阿', "E");
        PINYIN_MAP.put('恶', "E");
        PINYIN_MAP.put('恩', "E");
        PINYIN_MAP.put('儿', "E");
        PINYIN_MAP.put('耳', "E");
        PINYIN_MAP.put('而', "E");
        PINYIN_MAP.put('二', "E");
        // F
        PINYIN_MAP.put('法', "F");
        PINYIN_MAP.put('发', "F");
        PINYIN_MAP.put('反', "F");
        PINYIN_MAP.put('范', "F");
        PINYIN_MAP.put('方', "F");
        PINYIN_MAP.put('房', "F");
        PINYIN_MAP.put('防', "F");
        PINYIN_MAP.put('放', "F");
        PINYIN_MAP.put('非', "F");
        PINYIN_MAP.put('飞', "F");
        PINYIN_MAP.put('费', "F");
        PINYIN_MAP.put('份', "F");
        PINYIN_MAP.put('分', "F");
        PINYIN_MAP.put('风', "F");
        PINYIN_MAP.put('封', "F");
        PINYIN_MAP.put('夫', "F");
        PINYIN_MAP.put('服', "F");
        PINYIN_MAP.put('福', "F");
        PINYIN_MAP.put('府', "F");
        PINYIN_MAP.put('父', "F");
        PINYIN_MAP.put('复', "F");
        PINYIN_MAP.put('付', "F");
        PINYIN_MAP.put('副', "F");
        PINYIN_MAP.put('富', "F");
        // G
        PINYIN_MAP.put('改', "G");
        PINYIN_MAP.put('敢', "G");
        PINYIN_MAP.put('感', "G");
        PINYIN_MAP.put('刚', "G");
        PINYIN_MAP.put('钢', "G");
        PINYIN_MAP.put('高', "G");
        PINYIN_MAP.put('搞', "G");
        PINYIN_MAP.put('告', "G");
        PINYIN_MAP.put('歌', "G");
        PINYIN_MAP.put('格', "G");
        PINYIN_MAP.put('个', "G");
        PINYIN_MAP.put('给', "G");
        PINYIN_MAP.put('根', "G");
        PINYIN_MAP.put('跟', "G");
        PINYIN_MAP.put('更', "G");
        PINYIN_MAP.put('工', "G");
        PINYIN_MAP.put('公', "G");
        PINYIN_MAP.put('功', "G");
        PINYIN_MAP.put('共', "G");
        PINYIN_MAP.put('构', "G");
        PINYIN_MAP.put('姑', "G");
        PINYIN_MAP.put('古', "G");
        PINYIN_MAP.put('骨', "G");
        PINYIN_MAP.put('固', "G");
        PINYIN_MAP.put('故', "G");
        PINYIN_MAP.put('顾', "G");
        PINYIN_MAP.put('瓜', "G");
        PINYIN_MAP.put('刮', "G");
        PINYIN_MAP.put('关', "G");
        PINYIN_MAP.put('观', "G");
        PINYIN_MAP.put('官', "G");
        PINYIN_MAP.put('管', "G");
        PINYIN_MAP.put('光', "G");
        PINYIN_MAP.put('广', "G");
        PINYIN_MAP.put('规', "G");
        PINYIN_MAP.put('归', "G");
        PINYIN_MAP.put('贵', "G");
        PINYIN_MAP.put('国', "G");
        PINYIN_MAP.put('果', "G");
        PINYIN_MAP.put('过', "G");
        // H
        PINYIN_MAP.put('哈', "H");
        PINYIN_MAP.put('孩', "H");
        PINYIN_MAP.put('海', "H");
        PINYIN_MAP.put('含', "H");
        PINYIN_MAP.put('汉', "H");
        PINYIN_MAP.put('好', "H");
        PINYIN_MAP.put('合', "H");
        PINYIN_MAP.put('和', "H");
        PINYIN_MAP.put('何', "H");
        PINYIN_MAP.put('河', "H");
        PINYIN_MAP.put('核', "H");
        PINYIN_MAP.put('黑', "H");
        PINYIN_MAP.put('红', "H");
        PINYIN_MAP.put('后', "H");
        PINYIN_MAP.put('呼', "H");
        PINYIN_MAP.put('乎', "H");
        PINYIN_MAP.put('胡', "H");
        PINYIN_MAP.put('湖', "H");
        PINYIN_MAP.put('护', "H");
        PINYIN_MAP.put('花', "H");
        PINYIN_MAP.put('华', "H");
        PINYIN_MAP.put('化', "H");
        PINYIN_MAP.put('画', "H");
        PINYIN_MAP.put('话', "H");
        PINYIN_MAP.put('欢', "H");
        PINYIN_MAP.put('换', "H");
        PINYIN_MAP.put('黄', "H");
        PINYIN_MAP.put('回', "H");
        PINYIN_MAP.put('会', "H");
        PINYIN_MAP.put('婚', "H");
        PINYIN_MAP.put('活', "H");
        PINYIN_MAP.put('火', "H");
        PINYIN_MAP.put('获', "H");
        PINYIN_MAP.put('或', "H");
        // J
        PINYIN_MAP.put('机', "J");
        PINYIN_MAP.put('基', "J");
        PINYIN_MAP.put('极', "J");
        PINYIN_MAP.put('急', "J");
        PINYIN_MAP.put('集', "J");
        PINYIN_MAP.put('计', "J");
        PINYIN_MAP.put('记', "J");
        PINYIN_MAP.put('纪', "J");
        PINYIN_MAP.put('技', "J");
        PINYIN_MAP.put('季', "J");
        PINYIN_MAP.put('家', "J");
        PINYIN_MAP.put('加', "J");
        PINYIN_MAP.put('假', "J");
        PINYIN_MAP.put('价', "J");
        PINYIN_MAP.put('间', "J");
        PINYIN_MAP.put('简', "J");
        PINYIN_MAP.put('建', "J");
        PINYIN_MAP.put('健', "J");
        PINYIN_MAP.put('江', "J");
        PINYIN_MAP.put('将', "J");
        PINYIN_MAP.put('交', "J");
        PINYIN_MAP.put('角', "J");
        PINYIN_MAP.put('脚', "J");
        PINYIN_MAP.put('叫', "J");
        PINYIN_MAP.put('教', "J");
        PINYIN_MAP.put('接', "J");
        PINYIN_MAP.put('节', "J");
        PINYIN_MAP.put('结', "J");
        PINYIN_MAP.put('姐', "J");
        PINYIN_MAP.put('解', "J");
        PINYIN_MAP.put('介', "J");
        PINYIN_MAP.put('界', "J");
        PINYIN_MAP.put('金', "J");
        PINYIN_MAP.put('今', "J");
        PINYIN_MAP.put('进', "J");
        PINYIN_MAP.put('近', "J");
        PINYIN_MAP.put('精', "J");
        PINYIN_MAP.put('景', "J");
        PINYIN_MAP.put('静', "J");
        PINYIN_MAP.put('究', "J");
        PINYIN_MAP.put('九', "J");
        PINYIN_MAP.put('久', "J");
        PINYIN_MAP.put('酒', "J");
        PINYIN_MAP.put('旧', "J");
        PINYIN_MAP.put('就', "J");
        PINYIN_MAP.put('局', "J");
        PINYIN_MAP.put('居', "J");
        PINYIN_MAP.put('举', "J");
        PINYIN_MAP.put('具', "J");
        PINYIN_MAP.put('句', "J");
        PINYIN_MAP.put('觉', "J");
        PINYIN_MAP.put('决', "J");
        PINYIN_MAP.put('军', "J");
        // K
        PINYIN_MAP.put('卡', "K");
        PINYIN_MAP.put('开', "K");
        PINYIN_MAP.put('看', "K");
        PINYIN_MAP.put('康', "K");
        PINYIN_MAP.put('考', "K");
        PINYIN_MAP.put('靠', "K");
        PINYIN_MAP.put('科', "K");
        PINYIN_MAP.put('可', "K");
        PINYIN_MAP.put('课', "K");
        PINYIN_MAP.put('肯', "K");
        PINYIN_MAP.put('空', "K");
        PINYIN_MAP.put('口', "K");
        PINYIN_MAP.put('苦', "K");
        PINYIN_MAP.put('库', "K");
        PINYIN_MAP.put('快', "K");
        PINYIN_MAP.put('宽', "K");
        PINYIN_MAP.put('款', "K");
        PINYIN_MAP.put('况', "K");
        // L
        PINYIN_MAP.put('拉', "L");
        PINYIN_MAP.put('来', "L");
        PINYIN_MAP.put('蓝', "L");
        PINYIN_MAP.put('老', "L");
        PINYIN_MAP.put('乐', "L");
        PINYIN_MAP.put('李', "L");
        PINYIN_MAP.put('里', "L");
        PINYIN_MAP.put('理', "L");
        PINYIN_MAP.put('力', "L");
        PINYIN_MAP.put('立', "L");
        PINYIN_MAP.put('利', "L");
        PINYIN_MAP.put('连', "L");
        PINYIN_MAP.put('良', "L");
        PINYIN_MAP.put('亮', "L");
        PINYIN_MAP.put('了', "L");
        PINYIN_MAP.put('列', "L");
        PINYIN_MAP.put('林', "L");
        PINYIN_MAP.put('灵', "L");
        PINYIN_MAP.put('领', "L");
        PINYIN_MAP.put('流', "L");
        PINYIN_MAP.put('留', "L");
        PINYIN_MAP.put('六', "L");
        PINYIN_MAP.put('龙', "L");
        PINYIN_MAP.put('楼', "L");
        PINYIN_MAP.put('路', "L");
        PINYIN_MAP.put('录', "L");
        PINYIN_MAP.put('陆', "L");
        PINYIN_MAP.put('伦', "L");
        PINYIN_MAP.put('罗', "L");
        PINYIN_MAP.put('绿', "L");
        PINYIN_MAP.put('律', "L");
        PINYIN_MAP.put('乱', "L");
        PINYIN_MAP.put('略', "L");
        PINYIN_MAP.put('论', "L");
        // M
        PINYIN_MAP.put('马', "M");
        PINYIN_MAP.put('买', "M");
        PINYIN_MAP.put('卖', "M");
        PINYIN_MAP.put('满', "M");
        PINYIN_MAP.put('慢', "M");
        PINYIN_MAP.put('忙', "M");
        PINYIN_MAP.put('毛', "M");
        PINYIN_MAP.put('美', "M");
        PINYIN_MAP.put('门', "M");
        PINYIN_MAP.put('们', "M");
        PINYIN_MAP.put('米', "M");
        PINYIN_MAP.put('密', "M");
        PINYIN_MAP.put('面', "M");
        PINYIN_MAP.put('民', "M");
        PINYIN_MAP.put('明', "M");
        PINYIN_MAP.put('名', "M");
        PINYIN_MAP.put('命', "M");
        PINYIN_MAP.put('模', "M");
        PINYIN_MAP.put('莫', "M");
        PINYIN_MAP.put('母', "M");
        PINYIN_MAP.put('木', "M");
        PINYIN_MAP.put('目', "M");
        // N
        PINYIN_MAP.put('那', "N");
        PINYIN_MAP.put('拿', "N");
        PINYIN_MAP.put('哪', "N");
        PINYIN_MAP.put('内', "N");
        PINYIN_MAP.put('男', "N");
        PINYIN_MAP.put('南', "N");
        PINYIN_MAP.put('难', "N");
        PINYIN_MAP.put('能', "N");
        PINYIN_MAP.put('尼', "N");
        PINYIN_MAP.put('你', "N");
        PINYIN_MAP.put('年', "N");
        PINYIN_MAP.put('念', "N");
        PINYIN_MAP.put('鸟', "N");
        PINYIN_MAP.put('您', "N");
        PINYIN_MAP.put('牛', "N");
        PINYIN_MAP.put('农', "N");
        // O
        PINYIN_MAP.put('哦', "O");
        PINYIN_MAP.put('欧', "O");
        PINYIN_MAP.put('偶', "O");
        // P
        PINYIN_MAP.put('排', "P");
        PINYIN_MAP.put('派', "P");
        PINYIN_MAP.put('盘', "P");
        PINYIN_MAP.put('判', "P");
        PINYIN_MAP.put('跑', "P");
        PINYIN_MAP.put('配', "P");
        PINYIN_MAP.put('朋', "P");
        PINYIN_MAP.put('皮', "P");
        PINYIN_MAP.put('片', "P");
        PINYIN_MAP.put('平', "P");
        PINYIN_MAP.put('评', "P");
        PINYIN_MAP.put('瓶', "P");
        PINYIN_MAP.put('坡', "P");
        PINYIN_MAP.put('破', "P");
        PINYIN_MAP.put('普', "P");
        // Q
        PINYIN_MAP.put('七', "Q");
        PINYIN_MAP.put('期', "Q");
        PINYIN_MAP.put('其', "Q");
        PINYIN_MAP.put('奇', "Q");
        PINYIN_MAP.put('起', "Q");
        PINYIN_MAP.put('气', "Q");
        PINYIN_MAP.put('汽', "Q");
        PINYIN_MAP.put('千', "Q");
        PINYIN_MAP.put('前', "Q");
        PINYIN_MAP.put('钱', "Q");
        PINYIN_MAP.put('强', "Q");
        PINYIN_MAP.put('桥', "Q");
        PINYIN_MAP.put('巧', "Q");
        PINYIN_MAP.put('切', "Q");
        PINYIN_MAP.put('且', "Q");
        PINYIN_MAP.put('亲', "Q");
        PINYIN_MAP.put('轻', "Q");
        PINYIN_MAP.put('青', "Q");
        PINYIN_MAP.put('清', "Q");
        PINYIN_MAP.put('情', "Q");
        PINYIN_MAP.put('庆', "Q");
        PINYIN_MAP.put('秋', "Q");
        PINYIN_MAP.put('求', "Q");
        PINYIN_MAP.put('球', "Q");
        PINYIN_MAP.put('区', "Q");
        PINYIN_MAP.put('曲', "Q");
        PINYIN_MAP.put('取', "Q");
        PINYIN_MAP.put('去', "Q");
        PINYIN_MAP.put('全', "Q");
        PINYIN_MAP.put('缺', "Q");
        PINYIN_MAP.put('确', "Q");
        PINYIN_MAP.put('群', "Q");
        // R
        PINYIN_MAP.put('然', "R");
        PINYIN_MAP.put('让', "R");
        PINYIN_MAP.put('热', "R");
        PINYIN_MAP.put('人', "R");
        PINYIN_MAP.put('仁', "R");
        PINYIN_MAP.put('任', "R");
        PINYIN_MAP.put('日', "R");
        PINYIN_MAP.put('容', "R");
        PINYIN_MAP.put('肉', "R");
        PINYIN_MAP.put('如', "R");
        PINYIN_MAP.put('入', "R");
        PINYIN_MAP.put('若', "R");
        PINYIN_MAP.put('弱', "R");
        // S
        PINYIN_MAP.put('三', "S");
        PINYIN_MAP.put('色', "S");
        PINYIN_MAP.put('森', "S");
        PINYIN_MAP.put('沙', "S");
        PINYIN_MAP.put('山', "S");
        PINYIN_MAP.put('善', "S");
        PINYIN_MAP.put('商', "S");
        PINYIN_MAP.put('上', "S");
        PINYIN_MAP.put('少', "S");
        PINYIN_MAP.put('绍', "S");
        PINYIN_MAP.put('社', "S");
        PINYIN_MAP.put('设', "S");
        PINYIN_MAP.put('申', "S");
        PINYIN_MAP.put('身', "S");
        PINYIN_MAP.put('深', "S");
        PINYIN_MAP.put('什', "S");
        PINYIN_MAP.put('生', "S");
        PINYIN_MAP.put('声', "S");
        PINYIN_MAP.put('胜', "S");
        PINYIN_MAP.put('师', "S");
        PINYIN_MAP.put('施', "S");
        PINYIN_MAP.put('十', "S");
        PINYIN_MAP.put('时', "S");
        PINYIN_MAP.put('事', "S");
        PINYIN_MAP.put('手', "S");
        PINYIN_MAP.put('守', "S");
        PINYIN_MAP.put('首', "S");
        PINYIN_MAP.put('受', "S");
        PINYIN_MAP.put('书', "S");
        PINYIN_MAP.put('术', "S");
        PINYIN_MAP.put('树', "S");
        PINYIN_MAP.put('数', "S");
        PINYIN_MAP.put('双', "S");
        PINYIN_MAP.put('水', "S");
        PINYIN_MAP.put('税', "S");
        PINYIN_MAP.put('睡', "S");
        PINYIN_MAP.put('思', "S");
        PINYIN_MAP.put('四', "S");
        PINYIN_MAP.put('送', "S");
        PINYIN_MAP.put('诉', "S");
        PINYIN_MAP.put('算', "S");
        PINYIN_MAP.put('随', "S");
        PINYIN_MAP.put('岁', "S");
        PINYIN_MAP.put('所', "S");
        PINYIN_MAP.put('索', "S");
        // T
        PINYIN_MAP.put('他', "T");
        PINYIN_MAP.put('它', "T");
        PINYIN_MAP.put('她', "T");
        PINYIN_MAP.put('台', "T");
        PINYIN_MAP.put('太', "T");
        PINYIN_MAP.put('态', "T");
        PINYIN_MAP.put('谈', "T");
        PINYIN_MAP.put('特', "T");
        PINYIN_MAP.put('提', "T");
        PINYIN_MAP.put('题', "T");
        PINYIN_MAP.put('体', "T");
        PINYIN_MAP.put('天', "T");
        PINYIN_MAP.put('填', "T");
        PINYIN_MAP.put('条', "T");
        PINYIN_MAP.put('铁', "T");
        PINYIN_MAP.put('听', "T");
        PINYIN_MAP.put('停', "T");
        PINYIN_MAP.put('通', "T");
        PINYIN_MAP.put('同', "T");
        PINYIN_MAP.put('统', "T");
        PINYIN_MAP.put('头', "T");
        PINYIN_MAP.put('图', "T");
        PINYIN_MAP.put('土', "T");
        PINYIN_MAP.put('团', "T");
        PINYIN_MAP.put('推', "T");
        PINYIN_MAP.put('退', "T");
        // W
        PINYIN_MAP.put('瓦', "W");
        PINYIN_MAP.put('外', "W");
        PINYIN_MAP.put('完', "W");
        PINYIN_MAP.put('玩', "W");
        PINYIN_MAP.put('晚', "W");
        PINYIN_MAP.put('王', "W");
        PINYIN_MAP.put('万', "W");
        PINYIN_MAP.put('往', "W");
        PINYIN_MAP.put('忘', "W");
        PINYIN_MAP.put('望', "W");
        PINYIN_MAP.put('威', "W");
        PINYIN_MAP.put('伟', "W");
        PINYIN_MAP.put('为', "W");
        PINYIN_MAP.put('位', "W");
        PINYIN_MAP.put('文', "W");
        PINYIN_MAP.put('闻', "W");
        PINYIN_MAP.put('问', "W");
        PINYIN_MAP.put('翁', "W");
        PINYIN_MAP.put('我', "W");
        PINYIN_MAP.put('无', "W");
        PINYIN_MAP.put('五', "W");
        PINYIN_MAP.put('物', "W");
        PINYIN_MAP.put('务', "W");
        PINYIN_MAP.put('误', "W");
        // X
        PINYIN_MAP.put('西', "X");
        PINYIN_MAP.put('希', "X");
        PINYIN_MAP.put('系', "X");
        PINYIN_MAP.put('息', "X");
        PINYIN_MAP.put('喜', "X");
        PINYIN_MAP.put('细', "X");
        PINYIN_MAP.put('下', "X");
        PINYIN_MAP.put('夏', "X");
        PINYIN_MAP.put('先', "X");
        PINYIN_MAP.put('仙', "X");
        PINYIN_MAP.put('显', "X");
        PINYIN_MAP.put('示', "X");
        PINYIN_MAP.put('香', "X");
        PINYIN_MAP.put('乡', "X");
        PINYIN_MAP.put('相', "X");
        PINYIN_MAP.put('向', "X");
        PINYIN_MAP.put('项', "X");
        PINYIN_MAP.put('小', "X");
        PINYIN_MAP.put('笑', "X");
        PINYIN_MAP.put('校', "X");
        PINYIN_MAP.put('些', "X");
        PINYIN_MAP.put('谢', "X");
        PINYIN_MAP.put('心', "X");
        PINYIN_MAP.put('新', "X");
        PINYIN_MAP.put('信', "X");
        PINYIN_MAP.put('星', "X");
        PINYIN_MAP.put('形', "X");
        PINYIN_MAP.put('修', "X");
        PINYIN_MAP.put('须', "X");
        PINYIN_MAP.put('许', "X");
        PINYIN_MAP.put('续', "X");
        PINYIN_MAP.put('学', "X");
        PINYIN_MAP.put('雪', "X");
        PINYIN_MAP.put('血', "X");
        PINYIN_MAP.put('寻', "X");
        PINYIN_MAP.put('训', "X");
        PINYIN_MAP.put('讯', "X");
        // Y
        PINYIN_MAP.put('压', "Y");
        PINYIN_MAP.put('呀', "Y");
        PINYIN_MAP.put('牙', "Y");
        PINYIN_MAP.put('亚', "Y");
        PINYIN_MAP.put('烟', "Y");
        PINYIN_MAP.put('严', "Y");
        PINYIN_MAP.put('研', "Y");
        PINYIN_MAP.put('言', "Y");
        PINYIN_MAP.put('颜', "Y");
        PINYIN_MAP.put('眼', "Y");
        PINYIN_MAP.put('演', "Y");
        PINYIN_MAP.put('阳', "Y");
        PINYIN_MAP.put('养', "Y");
        PINYIN_MAP.put('要', "Y");
        PINYIN_MAP.put('也', "Y");
        PINYIN_MAP.put('业', "Y");
        PINYIN_MAP.put('叶', "Y");
        PINYIN_MAP.put('夜', "Y");
        PINYIN_MAP.put('一', "Y");
        PINYIN_MAP.put('医', "Y");
        PINYIN_MAP.put('衣', "Y");
        PINYIN_MAP.put('依', "Y");
        PINYIN_MAP.put('疑', "Y");
        PINYIN_MAP.put('已', "Y");
        PINYIN_MAP.put('以', "Y");
        PINYIN_MAP.put('用', "Y");
        PINYIN_MAP.put('由', "Y");
        PINYIN_MAP.put('游', "Y");
        PINYIN_MAP.put('友', "Y");
        PINYIN_MAP.put('有', "Y");
        PINYIN_MAP.put('又', "Y");
        PINYIN_MAP.put('右', "Y");
        PINYIN_MAP.put('于', "Y");
        PINYIN_MAP.put('鱼', "Y");
        PINYIN_MAP.put('雨', "Y");
        PINYIN_MAP.put('语', "Y");
        PINYIN_MAP.put('玉', "Y");
        PINYIN_MAP.put('元', "Y");
        PINYIN_MAP.put('员', "Y");
        PINYIN_MAP.put('原', "Y");
        PINYIN_MAP.put('远', "Y");
        PINYIN_MAP.put('院', "Y");
        PINYIN_MAP.put('月', "Y");
        PINYIN_MAP.put('越', "Y");
        PINYIN_MAP.put('云', "Y");
        PINYIN_MAP.put('运', "Y");
        // Z
        PINYIN_MAP.put('杂', "Z");
        PINYIN_MAP.put('在', "Z");
        PINYIN_MAP.put('早', "Z");
        PINYIN_MAP.put('造', "Z");
        PINYIN_MAP.put('则', "Z");
        PINYIN_MAP.put('增', "Z");
        PINYIN_MAP.put('展', "Z");
        PINYIN_MAP.put('站', "Z");
        PINYIN_MAP.put('张', "Z");
        PINYIN_MAP.put('章', "Z");
        PINYIN_MAP.put('招', "Z");
        PINYIN_MAP.put('找', "Z");
        PINYIN_MAP.put('照', "Z");
        PINYIN_MAP.put('者', "Z");
        PINYIN_MAP.put('这', "Z");
        PINYIN_MAP.put('真', "Z");
        PINYIN_MAP.put('正', "Z");
        PINYIN_MAP.put('整', "Z");
        PINYIN_MAP.put('政', "Z");
        PINYIN_MAP.put('之', "Z");
        PINYIN_MAP.put('支', "Z");
        PINYIN_MAP.put('知', "Z");
        PINYIN_MAP.put('直', "Z");
        PINYIN_MAP.put('值', "Z");
        PINYIN_MAP.put('职', "Z");
        PINYIN_MAP.put('指', "Z");
        PINYIN_MAP.put('止', "Z");
        PINYIN_MAP.put('至', "Z");
        PINYIN_MAP.put('志', "Z");
        PINYIN_MAP.put('制', "Z");
        PINYIN_MAP.put('治', "Z");
        PINYIN_MAP.put('中', "Z");
        PINYIN_MAP.put('钟', "Z");
        PINYIN_MAP.put('终', "Z");
        PINYIN_MAP.put('种', "Z");
        PINYIN_MAP.put('重', "Z");
        PINYIN_MAP.put('众', "Z");
        PINYIN_MAP.put('周', "Z");
        PINYIN_MAP.put('州', "Z");
        PINYIN_MAP.put('朱', "Z");
        PINYIN_MAP.put('主', "Z");
        PINYIN_MAP.put('住', "Z");
        PINYIN_MAP.put('注', "Z");
        PINYIN_MAP.put('祝', "Z");
        PINYIN_MAP.put('专', "Z");
        PINYIN_MAP.put('转', "Z");
        PINYIN_MAP.put('赚', "Z");
        PINYIN_MAP.put('准', "Z");
        PINYIN_MAP.put('桌', "Z");
        PINYIN_MAP.put('资', "Z");
        PINYIN_MAP.put('子', "Z");
        PINYIN_MAP.put('字', "Z");
        PINYIN_MAP.put('自', "Z");
        PINYIN_MAP.put('总', "Z");
        PINYIN_MAP.put('走', "Z");
        PINYIN_MAP.put('租', "Z");
        PINYIN_MAP.put('组', "Z");
        PINYIN_MAP.put('最', "Z");
        PINYIN_MAP.put('左', "Z");
        PINYIN_MAP.put('作', "Z");
        PINYIN_MAP.put('做', "Z");
        PINYIN_MAP.put('坐', "Z");
        PINYIN_MAP.put('座', "Z");
    }

    /**
     * 私有构造器，防止实例化
     */
    private PinyinUtil() {
    }

    /**
     * 获取字符的拼音首字母
     *
     * @param ch 字符
     * @return 拼音首字母（大写），非中文字符返回原字符的大写形式
     */
    public static String getFirstLetter(char ch) {
        // 字母和数字直接返回大写
        if ((ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9')) {
            return String.valueOf(Character.toUpperCase(ch));
        }
        // 查找拼音映射
        String letter = PINYIN_MAP.get(ch);
        return letter != null ? letter : "#";
    }

    /**
     * 获取字符串的拼音首字母字符串
     *
     * @param str 输入字符串
     * @return 拼音首字母字符串（大写），非中文字符保持原样
     */
    public static String getFirstLetter(String str) {
        if (str == null || str.isEmpty()) {
            return "";
        }
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < str.length(); i++) {
            result.append(getFirstLetter(str.charAt(i)));
        }
        return result.toString();
    }

    /**
     * 判断文本是否匹配关键词（支持拼音首字母匹配）
     *
     * @param text     原始文本
     * @param keyword  搜索关键词
     * @return 是否匹配
     */
    public static boolean matches(String text, String keyword) {
        if (text == null || keyword == null || keyword.isEmpty()) {
            return false;
        }
        String textLower = text.toLowerCase();
        String keywordLower = keyword.toLowerCase();
        // 直接匹配
        if (textLower.contains(keywordLower)) {
            return true;
        }
        // 拼音首字母匹配
        String pinyin = getFirstLetter(text);
        return pinyin.toLowerCase().contains(keywordLower);
    }
}
