/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatInput: typeof import('./components/Chat/ChatInput.vue')['default']
    ChunkUpload: typeof import('./components/Upload/ChunkUpload.vue')['default']
    CodeEditor: typeof import('./components/Chat/CodeEditor.vue')['default']
    DictTag: typeof import('./components/DictTag/index.vue')['default']
    Editor: typeof import('./components/Editor/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElAvatarGroup: typeof import('element-plus/es')['ElAvatarGroup']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmojiPicker: typeof import('./components/Chat/EmojiPicker.vue')['default']
    ErrorHandler: typeof import('./components/ErrorHandler.vue')['default']
    FilePreview: typeof import('./components/FilePreview/index.vue')['default']
    ImagePreview: typeof import('./components/Chat/ImagePreview.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload/index.vue')['default']
    MeetingDialog: typeof import('./components/MeetingDialog/index.vue')['default']
    MentionSelector: typeof import('./components/Chat/MentionSelector.vue')['default']
    MessageBubble: typeof import('./components/Chat/MessageBubble.vue')['default']
    MessageList: typeof import('./components/Chat/MessageList.vue')['default']
    Pagination: typeof import('./components/Pagination/index.vue')['default']
    QuickReply: typeof import('./components/Chat/QuickReply.vue')['default']
    RightToolbar: typeof import('./components/RightToolbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionList: typeof import('./components/Chat/SessionList.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    ThemeSwitch: typeof import('./components/ThemeSwitch/index.vue')['default']
    Upload: typeof import('./components/Upload/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
